name: make `make dist` tarball
on:
  workflow_dispatch:
  push:
    tags:
      - release/**
      - v**

env:
  # For caching APT packages
  APT_CACHE_RESTORE_KEYS: |
    apt-cache-${{ runner.os }}-makedist

jobs:
  amazonlinux:
    strategy:
      matrix:
        container:
          - public.ecr.aws/amazonlinux/amazonlinux:2023
        efainstaller:
          - latest
        displayname:
          - al2023
        efainstallerdir:
          - ALINUX2023
        nvidiadistro:
          - amzn2023
        configmanager:
          - dnf config-manager
        cudapackages:
          - cuda-cudart-devel-12-6 cuda-crt-12-6

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    name: make dist for tag ${{ github.ref_name }}
    steps:
      - name: Setup YUM Cache
        uses: actions/cache@v3
        id: yum-cache
        with:
          path: /var/cache/yum
          key: yum-cache-${{ runner.os }}-${{ hashFiles('**/workflows/tag-makedist.yaml') }}
          restore-keys: |
            yum-cache-${{ runner.os }}-
      
      - run: |
          # Configure YUM to keep cache
          echo 'keepcache=1' | tee -a /etc/yum.conf
          # Add retry logic
          for i in {1..3}; do
            if yum -y update && yum -y install git tar util-linux findutils yum-utils; then
              break
            fi
            echo "Retrying yum in 10 seconds..."
            sleep 10
          done
      - uses: actions/checkout@v4
      - name: Fetch and Install EFA Installer Dependencies
        run: |
          # Add retry logic for curl
          for i in {1..3}; do
            if curl -O https://efa-installer.amazonaws.com/aws-efa-installer-${{ matrix.efainstaller }}.tar.gz; then
              break
            fi
            echo "Retrying curl in 10 seconds..."
            sleep 10
          done
          tar -xf aws-efa-installer-*.tar.gz
          # Install EFA RPMs from local directory to avoid network issues
          ( cd aws-efa-installer/RPMS/${{ matrix.efainstallerdir }}/x86_64 ; find . | grep rpm$ | xargs yum -y localinstall )
          rm -rf aws-efa-installer*

      - name: Install hwloc, utilities.
        run: |
          # Add retry logic for package installation
          for i in {1..3}; do
            if yum -y install hwloc-devel autoconf automake libtool gcc gcc-c++ git make; then
              break
            fi
            echo "Retrying yum in 10 seconds..."
            sleep 10
          done

      - name: Install CUDA
        run: |
          # Add retry logic for repo config
          for i in {1..3}; do
            if ${{ matrix.configmanager }} --add-repo \
               http://developer.download.nvidia.com/compute/cuda/repos/${{ matrix.nvidiadistro }}/x86_64/cuda-${{ matrix.nvidiadistro }}.repo \
               --save; then
              break
            fi
            echo "Retrying repo add in 10 seconds..."
            sleep 10
          done
          
          # Clean and refresh cache
          yum -y clean expire-cache
          
          # Add retry logic for package installation
          for i in {1..3}; do
            if yum -y install ${{ matrix.cudapackages }}; then
              break
            fi
            echo "Retrying CUDA package installation in 10 seconds..."
            sleep 10
          done

      - name: Call `autoreconf -ivf`
        run: |
          ./autogen.sh
          ./configure --with-mpi=/opt/amazon/openmpi \
                      --with-libfabric=/opt/amazon/efa \
                      --enable-tests=yes \
                      --enable-werror=yes \
                      --enable-picky-compiler=yes \
                      --enable-platform-aws \
                      --with-cuda=/usr/local/cuda/

      - name: Call `make distcheck`
        run: make distcheck V=1

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ github.ref_name }} make dist output"
          path: "*.tar*"
          if-no-files-found: error
